import {useCallback,useEffect,useReducer,useRef,useState,type CSSProperties} from 'react';
import {House,Compass,Plus,ChatCircle,User,Heart,ShareNetwork,ArrowRight,ArrowUp,ArrowDown,Camera,CameraSlash,X,ArrowCounterClockwise,Info,Sparkle,Check,MusicNotes,SlidersHorizontal} from '@phosphor-icons/react';
import {identities,demoPortrait} from './content';
import {initialExperience,randomIdentity,reducer,stopStream} from './experience';
import FaceEffects from './FaceEffects';
import {memes,memeById,enclosure} from './memes';
import {useMemeSound} from './useMemeSound';
const base=import.meta.env.BASE_URL;
function phasePost(phase:string,history:string[],index:number){return phase==='feed'?memeById(history[index]||'shadow'):null;}
export default function App(){
 const [state,dispatch]=useReducer(reducer,initialExperience);const [stream,setStream]=useState<MediaStream|null>(null);const streamRef=useRef<MediaStream|null>(null);const video=useRef<HTMLVideoElement>(null);const requestId=useRef(0);const mounted=useRef(true);
 const [soundOn,setSoundOn]=useState(false);const viewed=useRef(new Set<string>());
 const [busy,setBusy]=useState(false),[cameraError,setCameraError]=useState(''),[tracking,setTracking]=useState('Camera off'),[toast,setToast]=useState(''),[modal,setModal]=useState<'about'|'profile'|'comments'|'explore'|'inbox'|null>(null),[liked,setLiked]=useState<Set<string>>(new Set()),[tab,setTab]=useState<'for-you'|'following'>('for-you'),[progress,setProgress]=useState(0);
 const identity=identities.find(i=>i.id===state.identity);const post=phasePost(state.phase,state.history,state.index);const currentKey=`${state.identity}-${state.index}`;const phase=state.phase;const scanned=phase==='identity'||phase==='feed';const scan=phase==='scanning'||phase==='resetting';const notify=useCallback((message:string)=>setToast(message),[]);const onTracking=useCallback((s:string)=>setTracking(s),[]);
 useMemeSound(post,soundOn&&phase==='feed');
 useEffect(()=>{if(phase!=='feed'||!post||modal||viewed.current.has(currentKey))return;const t=setTimeout(()=>{viewed.current.add(currentKey);dispatch({type:'interest',category:post.category,amount:1});},6500);return()=>clearTimeout(t);},[phase,post,currentKey,modal]);
 const closeCamera=useCallback(()=>{requestId.current++;stopStream(streamRef.current);streamRef.current=null;setStream(null);setBusy(false);setTracking('Camera off');},[]);
 const restart=()=>{closeCamera();setCameraError('');setLiked(new Set());viewed.current.clear();setTab('for-you');setModal(null);dispatch({type:'restart'});};
 useEffect(()=>{mounted.current=true;const release=()=>{requestId.current++;stopStream(streamRef.current);streamRef.current=null;setStream(null);};window.addEventListener('pagehide',release);return()=>{mounted.current=false;requestId.current++;stopStream(streamRef.current);window.removeEventListener('pagehide',release);};},[]);
 useEffect(()=>{const v=video.current;if(v&&stream){v.srcObject=stream;v.play().catch(()=>notify('Tap the camera preview to resume playback.'));}return()=>{if(v)v.srcObject=null;};},[stream,phase,notify]);
 useEffect(()=>{if(!scan)return;setProgress(0);const started=performance.now(),duration=phase==='resetting'?2400:3600;const interval=window.setInterval(()=>setProgress(Math.min(100,Math.round((performance.now()-started)/duration*100))),90);const timeout=window.setTimeout(()=>dispatch({type:'scanned'}),duration);return()=>{clearInterval(interval);clearTimeout(timeout);};},[scan,phase]);
 useEffect(()=>{if(phase==='ending')closeCamera();},[phase,closeCamera]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),3200);return()=>clearTimeout(t);},[toast]);
 const startDemo=()=>{closeCamera();dispatch({type:'start',identity:randomIdentity()});};
 const enableCamera=async()=>{if(phase==='ending'){notify('Start again to open a new camera session.');return;}if(busy)return;const token=++requestId.current;setBusy(true);setCameraError('');try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('unavailable');const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:720},height:{ideal:1280}},audio:false});if(token!==requestId.current||!mounted.current){stopStream(s);return;}stopStream(streamRef.current);streamRef.current=s;setStream(s);setBusy(false);if(phase==='welcome')dispatch({type:'start',identity:randomIdentity()});}catch(e){if(token!==requestId.current||!mounted.current)return;setBusy(false);const name=e instanceof DOMException?e.name:'';setCameraError(name==='NotAllowedError'?'Camera permission was declined. You can still explore the artwork in demo mode.':'No camera is available. Try again or enter demo mode.');}};
 const gestureLock=useRef(0),touchStart=useRef<number|null>(null);const step=useCallback((delta:number)=>{if(phase!=='feed'||modal)return;const now=performance.now();if(now-gestureLock.current<450)return;gestureLock.current=now;dispatch({type:'step',delta});},[phase,modal]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement).matches('input,textarea,select')||modal)return;if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();step(e.key==='ArrowDown'?1:-1);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[step,modal]);
 useEffect(()=>{if(!modal)return;const previous=document.activeElement as HTMLElement;const dialog=document.querySelector<HTMLDialogElement>('dialog');dialog?.showModal();const escape=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();setModal(null);}};window.addEventListener('keydown',escape);return()=>{dialog?.close();previous?.focus();window.removeEventListener('keydown',escape);};},[modal]);
 const share=async()=>{try{await navigator.clipboard.writeText(new URL(base,window.location.origin).href);notify('Artwork link copied.');}catch{setModal('about');notify('Copy the artwork link from About.');}};
 const nav=(value:'home'|'explore'|'create'|'inbox'|'profile')=>{if(value==='home'){setTab('for-you');setModal(null);}if(value==='explore')setModal('explore');if(value==='create'){if(stream)notify('Your camera is already on.');else void enableCamera();}if(value==='inbox')setModal('inbox');if(value==='profile')setModal('profile');};
 const toggleLike=()=>{const next=!liked.has(currentKey);setLiked(old=>{const n=new Set(old);next?n.add(currentKey):n.delete(currentKey);return n;});if(post){dispatch({type:'interest',category:post.category,amount:next?3:-3});if(next)notify('Noted. More of this coming up.');}};
 return <div className="app" style={{'--identity':identity?.color||'#53f5ed'} as CSSProperties}>
 <main className="stage-wrap"><section className={`stage ${phase} identity-${state.identity||'soft'} intensity-${phase==='feed'?Math.min(5,Math.floor(state.index/4)):0}`} aria-label="Interactive artwork" onWheel={e=>{if(Math.abs(e.deltaY)>20)step(e.deltaY>0?1:-1);}} onTouchStart={e=>{touchStart.current=e.touches[0].clientY;}} onTouchEnd={e=>{if(touchStart.current===null)return;const d=touchStart.current-e.changedTouches[0].clientY;if(Math.abs(d)>50)step(d>0?1:-1);touchStart.current=null;}}>
 {phase!=='ending'&&<><div className="portrait-backdrop">{stream?<video ref={video} className="camera-preview" autoPlay muted playsInline aria-label="Live camera preview" onClick={()=>video.current?.play()}/>:<img src={demoPortrait} alt="Fictional adult portrait for demo mode"/>}</div><div className="portrait-shade"/><div className="color-wash"/></>}
 <header className="stage-header"><div className="feed-tabs"><button className={tab==='following'?'active':''} onClick={()=>{setTab('following');notify('No creators followed. The platform chooses your feed.');}}>Following</button><button className={tab==='for-you'?'active':''} onClick={()=>setTab('for-you')}>For You</button></div><button className="camera-toggle" aria-label={stream?'Turn camera off':'Turn camera on'} onClick={()=>stream?closeCamera():void enableCamera()} disabled={busy}>{stream?<Camera size={18}/>:<CameraSlash size={18}/>}<span>{stream?'LIVE':'DEMO'}</span></button><button className="sound-toggle" aria-label={soundOn?'Mute meme sound':'Enable meme sound'} aria-pressed={soundOn} onClick={()=>setSoundOn(!soundOn)}><MusicNotes size={18}/><span>{soundOn?'ON':'OFF'}</span></button><button className="about-toggle" aria-label="About the artwork" onClick={()=>setModal('about')}><Info size={20}/></button></header>
 {(stream||phase==='feed')&&phase!=='ending'&&<FaceEffects video={video} active={!!stream||phase==='feed'} demo={!stream} identity={scanned?state.identity:null} effect={post?.id||null} index={state.index} onStatus={onTracking}/>}
 {phase!=='ending'&&<div className="scan-meta"><span>{stream?tracking:'DEMO / SAMPLE FACE'}</span><span>FOR YOU / REMIX</span></div>}
 {!stream&&scan&&<div className="scan-brackets" aria-hidden="true"><div className="scan-line"/></div>}
 {scan&&<div className="scan-copy"><span className="mono">{phase==='resetting'?'RECALCULATING IDENTITY':'CALIBRATING YOUR CHAOS'}</span><h1>{phase==='resetting'?'New scan.\nSame you.':'Hold still.\nGet memed.'}</h1><div className="scan-progress"><span style={{width:`${progress}%`}}/></div><div className="scan-stats mono"><span>SCAN {progress}%</span><span>{phase==='resetting'?'PROFILE LOCKED':'IDENTITY PENDING'}</span></div><p>{stream?'Face position is detected locally.':'Demo scan is simulated.'}<br/>Your personality is not.</p></div>}
 {phase==='welcome'&&<div className="welcome-copy"><div className="tiny-rule"/><span className="mono">YOUR FACE. OUR CONTENT STRATEGY.</span><h1>FOR<br/><em>YOU.</em></h1><p>Same face.<br/>Very different problems.</p><button className="primary" onClick={()=>void enableCamera()} disabled={busy}>{busy?'Opening camera…':'Make me a meme'}<ArrowRight size={22}/></button><button className="text-button" onClick={startDemo}>Try a sample <ArrowRight size={14}/></button><small>Camera stays on your device. No microphone.<br/>An interactive meme experiment.</small></div>}
 {phase==='identity'&&identity&&<><div className="static-face-frame" aria-hidden="true" hidden={!!stream}/><div className="identity-copy"><h1>YOU’RE<br/>OUR<br/><em>TYPE.</em></h1><div className="tiny-rule"/><p className="mono">FIRST GUESS:</p><h2>{identity.name}</h2><p className="identity-tags mono">{identity.tags.join(' / ')}</p><button className="deny-button" onClick={()=>{dispatch({type:'deny'});notify('Noted. Your profile remains unchanged.');}}>Wrong answer <ArrowRight size={22}/></button><button className="text-button" onClick={()=>dispatch({type:'feed'})}>Start scrolling <ArrowRight size={16}/></button></div></>}
 {phase==='feed'&&identity&&post&&<><div className="meme-headline" key={currentKey}><span className="meme-badge">{post.name} <b>{post.year}</b></span><h1>{post.title}</h1><p>{post.instruction}</p></div><div className="post-caption"><span className="mono">@foryou.remix · #{String(state.index+1).padStart(3,'0')}</span><p>{post.caption}</p><small><MusicNotes size={14}/>{soundOn?'meme voice + original electronic beat':'sound off · tap the music icon'}</small><button className="reset-button" onClick={()=>dispatch({type:'reset'})}><ArrowCounterClockwise size={14}/> Reset my feed</button></div>{state.index>=9&&<div className="loop-tag" aria-hidden="true">MORE LIKE YOU · {enclosure(state.interests)}%</div>}</>}
 {scanned&&<div className="action-rail"><button className="avatar" onClick={()=>setModal('profile')} aria-label="View assigned profile"><img src={demoPortrait} alt=""/><span><Plus size={12} weight="bold"/></span></button><button onClick={toggleLike} className={liked.has(currentKey)?'liked':''} aria-label="Like post" aria-pressed={liked.has(currentKey)}><Heart size={29} weight="fill"/><span>{liked.has(currentKey)?'128.5K':'128.4K'}</span></button><button onClick={()=>setModal('comments')} aria-label="Open comments"><ChatCircle size={29} weight="fill"/><span>4.2K</span></button><button onClick={()=>void share()} aria-label="Share artwork"><ShareNetwork size={28} weight="fill"/><span>9.1K</span></button></div>}
 {phase==='ending'&&<div className="ending-copy"><span className="mono">RECALCULATION COMPLETE</span><p className="same-result">Same result.</p><h1>Same face.<br/>Smaller <em>world.</em></h1><span className="ending-identity mono">{identity?.name} / STILL ASSIGNED</span><p>We started with a random label. Your likes and pauses shaped the next memes. Different costumes. A very familiar loop.</p><p className="ending-question">Do platforms understand us,<br/>or construct us?</p><button className="primary" onClick={restart}>Start again <ArrowRight size={20}/></button><button className="text-button" onClick={()=>setModal('about')}>Behind the experiment <Info size={15}/></button></div>}
 <nav className="bottom-nav" aria-label="Mobile navigation"><button onClick={()=>nav('home')}><House size={23} weight="fill"/><span>Home</span></button><button onClick={()=>nav('explore')}><Compass size={23}/><span>Explore</span></button><button className="create-button" onClick={()=>nav('create')} aria-label="Open camera"><Plus size={26} weight="bold"/></button><button onClick={()=>nav('inbox')}><ChatCircle size={23}/><span>Inbox</span></button><button onClick={()=>nav('profile')}><User size={23}/><span>Profile</span></button></nav>
 {toast&&<div className="toast" role="status"><Check size={15}/>{toast}</div>}
 {phase==='feed'&&<div className="scroll-controls"><button aria-label="Previous post" disabled={state.index===0} onClick={()=>step(-1)}><ArrowUp/></button><button aria-label="Next post" onClick={()=>step(1)}><ArrowDown/></button></div>}</section></main>
 {cameraError&&<div className="camera-error" role="alert"><CameraSlash size={20}/><p>{cameraError}</p><button onClick={()=>{setCameraError('');if(phase==='welcome')startDemo();}}>Continue in demo</button><button aria-label="Dismiss camera notice" onClick={()=>setCameraError('')}><X/></button></div>}
 {modal&&<dialog className="dialog" onCancel={()=>setModal(null)} onClick={e=>{if(e.target===e.currentTarget)setModal(null);}}><button className="dialog-close" onClick={()=>setModal(null)} aria-label="Close dialog"><X size={23}/></button>
 {modal==='about'&&<><span className="mono">BEHIND THE EXPERIMENT</span><h2>For you.<br/>According to whom?</h2><p>FOR YOU is a fictional platform and interactive artwork inspired by TikTok / Douyin. It turns your face into a meme, then lets your likes and viewing time narrow a simulated recommendation feed.</p><p>Camera frames and face landmarks stay in your browser. Face tracking positions effects; it does not identify you or infer personality. Identity labels and confidence-like visuals are fictional. The demo portrait is AI-generated.</p><p>The first nine effects are different. Later recommendations lean toward categories you like or watch. This is a small, fictional recommendation system, not a reconstruction of Douyin’s algorithm. Character artwork is AI-generated; cutout edges and glitch are part of the collage aesthetic.</p><label>Share the artwork<input readOnly value={new URL(base,window.location.origin).href} onFocus={e=>e.target.select()}/></label><span className="mono">ARTWORK / NOT A CLAIM ABOUT TIKTOK’S FACE ANALYSIS</span></>}
 {modal==='profile'&&<><span className="mono">YOUR ASSIGNED PROFILE</span><h2>{identity?.name||'Not yet defined.'}</h2><p>{identity?'You did not choose this identity. The system did.':'Enter the artwork to receive a fictional identity.'}</p><div className="profile-tags">{identity?.tags.map(t=><span key={t}>{t}</span>)}</div><p>Objections received: {state.denials}<br/>Feed preference: {enclosure(state.interests)}% concentrated</p>{scanned&&<button className="primary" onClick={()=>{setModal(null);dispatch({type:'reset'});}}>Reset my profile <ArrowCounterClockwise/></button>}</>}
 {modal==='comments'&&<><span className="mono">SIMULATED COMMUNITY</span><h2>Comments</h2>{(post?.comments||['That is not who I am.','The system seems very sure.','What happens if I disagree?']).map((c,i)=><div className="comment" key={c}><User size={22}/><div><span>@subject_{String(i+1).padStart(2,'0')}</span><p>{c}</p></div><Heart size={15}/></div>)}<p className="quiet">Fictional comments and engagement counts, part of the artwork.</p></>}
 {modal==='explore'&&<><span className="mono">THE PLATFORM’S CATEGORIES</span><h2>Pick your next<br/>mistake.</h2><p>Nine templates. One extremely reusable face. Tap a meme to break out of your current loop.</p>{memes.map(m=><button className="explore-meme" key={m.id} disabled={phase!=='feed'} onClick={()=>{dispatch({type:'discover',id:m.id});setModal(null);}}><span>{m.name}</span><small>{m.subtitle}</small><ArrowRight size={16}/></button>)}{identities.map(i=><div className="category" key={i.id} style={{color:i.color}}><span className="mono">TYPE {i.number}</span><h3>{i.name}</h3><p>{i.tags.join(' / ')}</p></div>)}</>}
 {modal==='inbox'&&<><span className="mono">SYSTEM MESSAGES</span><h2>We heard you.</h2><div className="comment"><ChatCircle size={23}/><p>{state.denials?'Your objection has been received. No profile changes are required.':'Your personalized world is ready. Your consent to a category was not required.'}</p></div><p className="quiet">A fictional message from a fictional platform.</p></>}
 </dialog>}
 </div>;
}
