import {useCallback,useEffect,useReducer,useRef,useState,type CSSProperties} from 'react';
import {House,Compass,Plus,ChatCircle,User,Heart,ShareNetwork,ArrowRight,ArrowUp,ArrowDown,Camera,CameraSlash,X,ArrowCounterClockwise,Info,Check} from '@phosphor-icons/react';
import {identities,demoPortrait} from './content';
import {initialExperience,randomIdentity,reducer,stopStream} from './experience';
import FaceTracking from './FaceTracking';
const base=import.meta.env.BASE_URL;
export default function App(){
 const [state,dispatch]=useReducer(reducer,initialExperience);const [stream,setStream]=useState<MediaStream|null>(null);const streamRef=useRef<MediaStream|null>(null);const video=useRef<HTMLVideoElement>(null);const requestId=useRef(0);const mounted=useRef(true);
 const [busy,setBusy]=useState(false),[cameraError,setCameraError]=useState(''),[tracking,setTracking]=useState('Camera off'),[toast,setToast]=useState(''),[modal,setModal]=useState<'about'|'profile'|'comments'|'explore'|'inbox'|null>(null),[tab,setTab]=useState<'for-you'|'following'>('for-you'),[progress,setProgress]=useState(0);
 const identity=identities.find(i=>i.id===state.identity);const phase=state.phase;const scanned=phase==='identity'||phase==='feed';const scan=phase==='scanning'||phase==='resetting';const notify=useCallback((message:string)=>setToast(message),[]);const onTracking=useCallback((s:string)=>setTracking(s),[]);
 const closeCamera=useCallback(()=>{requestId.current++;stopStream(streamRef.current);streamRef.current=null;setStream(null);setBusy(false);setTracking('Camera off');},[]);
 const restart=()=>{closeCamera();setCameraError('');setTab('for-you');setModal(null);dispatch({type:'restart'});};
 useEffect(()=>{mounted.current=true;const release=()=>{requestId.current++;stopStream(streamRef.current);streamRef.current=null;setStream(null);};window.addEventListener('pagehide',release);return()=>{mounted.current=false;requestId.current++;stopStream(streamRef.current);window.removeEventListener('pagehide',release);};},[]);
 useEffect(()=>{const v=video.current;if(v&&stream){v.srcObject=stream;v.play().catch(()=>notify('Tap the camera preview to resume playback.'));}return()=>{if(v)v.srcObject=null;};},[stream,phase,notify]);
 useEffect(()=>{if(!scan)return;setProgress(0);const started=performance.now(),duration=phase==='resetting'?2400:3600;const interval=window.setInterval(()=>setProgress(Math.min(100,Math.round((performance.now()-started)/duration*100))),90);const timeout=window.setTimeout(()=>dispatch({type:'scanned'}),duration);return()=>{clearInterval(interval);clearTimeout(timeout);};},[scan,phase]);
 useEffect(()=>{if(phase==='ending')closeCamera();},[phase,closeCamera]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),3200);return()=>clearTimeout(t);},[toast]);
 const startDemo=()=>{closeCamera();dispatch({type:'start',identity:randomIdentity()});};
 const enableCamera=async()=>{if(phase==='ending'){notify('Start again to open a new camera session.');return;}if(busy)return;const token=++requestId.current;setBusy(true);setCameraError('');try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('unavailable');const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:720},height:{ideal:1280}},audio:false});if(token!==requestId.current||!mounted.current){stopStream(s);return;}stopStream(streamRef.current);streamRef.current=s;setStream(s);setBusy(false);if(phase==='welcome')dispatch({type:'start',identity:randomIdentity()});}catch(e){if(token!==requestId.current||!mounted.current)return;setBusy(false);const name=e instanceof DOMException?e.name:'';setCameraError(name==='NotAllowedError'?'Camera permission was declined. You can still explore the artwork in demo mode.':'No camera is available. Try again or enter demo mode.');}};
 const gestureLock=useRef(0),touchStart=useRef<number|null>(null);const step=useCallback((delta:number)=>{if(phase!=='feed'||modal)return;const now=performance.now();if(now-gestureLock.current<450)return;gestureLock.current=now;dispatch({type:'step',delta});},[phase,modal]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement).matches('input,textarea,select')||modal)return;if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();step(e.key==='ArrowDown'?1:-1);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[step,modal]);
 useEffect(()=>{if(!modal)return;const previous=document.activeElement as HTMLElement;const dialog=document.querySelector<HTMLDialogElement>('dialog');dialog?.showModal();const escape=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();setModal(null);}};window.addEventListener('keydown',escape);return()=>{dialog?.close();previous?.focus();window.removeEventListener('keydown',escape);};},[modal]);
 const share=async()=>{try{await navigator.clipboard.writeText(new URL(base,window.location.origin).href);notify('Artwork link copied.');}catch{setModal('about');notify('Copy the artwork link from About.');}};
 const nav=(value:'home'|'explore'|'create'|'inbox'|'profile')=>{if(value==='home'){setTab('for-you');setModal(null);}if(value==='explore')setModal('explore');if(value==='create'){if(stream)notify('Your camera is already on.');else void enableCamera();}if(value==='inbox')setModal('inbox');if(value==='profile')setModal('profile');};
 return <div className="app" style={{'--identity':identity?.color||'#53f5ed'} as CSSProperties}>
 <main className="stage-wrap"><section className={`stage ${phase} identity-${state.identity||'soft'} skin-pirate intensity-${phase==='feed'?Math.min(5,Math.floor(state.index/4)):0}`} aria-label="Interactive artwork" onWheel={e=>{if(Math.abs(e.deltaY)>20)step(e.deltaY>0?1:-1);}} onTouchStart={e=>{touchStart.current=e.touches[0].clientY;}} onTouchEnd={e=>{if(touchStart.current===null)return;const d=touchStart.current-e.changedTouches[0].clientY;if(Math.abs(d)>50)step(d>0?1:-1);touchStart.current=null;}}>
 {phase!=='ending'&&<><div className="portrait-backdrop">{stream?<video ref={video} className="camera-preview" autoPlay muted playsInline aria-label="Live camera preview" onClick={()=>video.current?.play()}/>:<img src={demoPortrait} alt="Fictional adult portrait for demo mode"/>}</div><div className="portrait-shade"/><div className="color-wash"/></>}
 <div className="bootleg-brand"><strong>DOU.Y1N</strong><span>BOOTLEG VERSION</span></div><header className="stage-header"><div className="feed-tabs"><button className={tab==='following'?'active':''} onClick={()=>{setTab('following');notify('No creators followed. The platform chooses your feed.');}}>Following</button><button className={tab==='for-you'?'active':''} onClick={()=>setTab('for-you')}>For You</button></div><button className="camera-toggle" aria-label={stream?'Turn camera off':'Turn camera on'} onClick={()=>stream?closeCamera():void enableCamera()} disabled={busy}>{stream?<Camera size={18}/>:<CameraSlash size={18}/>}<span>{stream?'LIVE':'DEMO'}</span></button><button className="about-toggle" aria-label="About the artwork" onClick={()=>setModal('about')}><Info size={20}/></button></header>
 {stream&&phase!=='ending'&&<FaceTracking video={video} active={!!stream} onStatus={onTracking}/>}
 {phase!=='ending'&&<div className="scan-meta"><span>{stream?tracking:'DEMO / SAMPLE FACE'}</span><span>CAMERA / NO EFFECT</span></div>}
 {!stream&&scan&&<div className="scan-brackets" aria-hidden="true"><div className="scan-line"/></div>}
 {scan&&<div className="scan-copy"><span className="mono">{phase==='resetting'?'RECALCULATING IDENTITY':'CAMERA CHECK'}</span><h1>{phase==='resetting'?'New scan.\nSame you.':'Hold still.\nCamera preview.'}</h1><div className="scan-progress"><span style={{width:`${progress}%`}}/></div><div className="scan-stats mono"><span>SCAN {progress}%</span><span>{phase==='resetting'?'PROFILE LOCKED':'IDENTITY PENDING'}</span></div><p>{stream?'Face position is detected locally.':'Demo scan is simulated.'}<br/>Your personality is not.</p></div>}
 {phase==='welcome'&&<div className="welcome-copy"><div className="tiny-rule"/><span className="mono">YOUR FACE. OUR CONTENT STRATEGY.</span><h1>FOR<br/><em>Y0U?</em></h1><p>盗版信号，正版的你。<br/>Your face. Our bootleg feed.</p><button className="primary" onClick={()=>void enableCamera()} disabled={busy}>{busy?'Opening camera…':'Open camera'}<ArrowRight size={22}/></button><button className="text-button" onClick={startDemo}>Try a sample <ArrowRight size={14}/></button><small>Camera stays on your device. No microphone.<br/>No effects are active.</small></div>}
 {phase==='identity'&&identity&&<><div className="static-face-frame" aria-hidden="true" hidden={!!stream}/><div className="identity-copy"><h1>YOU’RE<br/>OUR<br/><em>TYPE.</em></h1><div className="tiny-rule"/><p className="mono">FIRST GUESS:</p><h2>{identity.name}</h2><p className="identity-tags mono">{identity.tags.join(' / ')}</p><button className="deny-button" onClick={()=>{dispatch({type:'deny'});notify('Noted. Your profile remains unchanged.');}}>Wrong answer <ArrowRight size={22}/></button><button className="text-button" onClick={()=>dispatch({type:'feed'})}>Start scrolling <ArrowRight size={16}/></button></div></>}
 {phase==='feed'&&<><div className="feed-empty" role="status"><h2>No effects</h2><p>The previous effects have been removed.</p></div><div className="post-caption"><span className="mono">CAMERA PREVIEW · #{String(state.index+1).padStart(3,'0')}</span><button className="reset-button" onClick={()=>dispatch({type:'reset'})}><ArrowCounterClockwise size={14}/> Reset my feed</button></div></>}
 {scanned&&<div className="action-rail"><button className="avatar" onClick={()=>setModal('profile')} aria-label="View assigned profile"><img src={demoPortrait} alt=""/><span><Plus size={12} weight="bold"/></span></button><button disabled aria-label="Like post"><Heart size={29} weight="fill"/><span>—</span></button><button onClick={()=>setModal('comments')} aria-label="Open comments"><ChatCircle size={29} weight="fill"/><span>4.2K</span></button><button onClick={()=>void share()} aria-label="Share artwork"><ShareNetwork size={28} weight="fill"/><span>9.1K</span></button></div>}
 {phase==='ending'&&<div className="ending-copy"><span className="mono">RECALCULATION COMPLETE</span><p className="same-result">Same result.</p><h1>Same face.<br/>Smaller <em>world.</em></h1><span className="ending-identity mono">{identity?.name} / STILL ASSIGNED</span><p>The effect collection has been cleared. Only the camera and interface remain.</p><p className="ending-question">Do platforms understand us,<br/>or construct us?</p><button className="primary" onClick={restart}>Start again <ArrowRight size={20}/></button><button className="text-button" onClick={()=>setModal('about')}>Behind the experiment <Info size={15}/></button></div>}
 <nav className="bottom-nav" aria-label="Mobile navigation"><button onClick={()=>nav('home')}><House size={23} weight="fill"/><span>Home</span></button><button onClick={()=>nav('explore')}><Compass size={23}/><span>Explore</span></button><button className="create-button" onClick={()=>nav('create')} aria-label="Open camera"><Plus size={26} weight="bold"/></button><button onClick={()=>nav('inbox')}><ChatCircle size={23}/><span>Inbox</span></button><button onClick={()=>nav('profile')}><User size={23}/><span>Profile</span></button></nav>
 {toast&&<div className="toast" role="status"><Check size={15}/>{toast}</div>}
 {phase==='feed'&&<div className="scroll-controls"><button aria-label="Previous post" disabled={state.index===0} onClick={()=>step(-1)}><ArrowUp/></button><button aria-label="Next post" onClick={()=>step(1)}><ArrowDown/></button></div>}</section></main>
 {cameraError&&<div className="camera-error" role="alert"><CameraSlash size={20}/><p>{cameraError}</p><button onClick={()=>{setCameraError('');if(phase==='welcome')startDemo();}}>Continue in demo</button><button aria-label="Dismiss camera notice" onClick={()=>setCameraError('')}><X/></button></div>}
 {modal&&<dialog className="dialog" onCancel={()=>setModal(null)} onClick={e=>{if(e.target===e.currentTarget)setModal(null);}}><button className="dialog-close" onClick={()=>setModal(null)} aria-label="Close dialog"><X size={23}/></button>
 {modal==='about'&&<><span className="mono">BEHIND THE EXPERIMENT</span><h2>For you.<br/>According to whom?</h2><p>FOR YOU is a fictional platform and interactive artwork inspired by TikTok / Douyin. The previous effect collection has been removed at the creator’s request. This version retains the camera preview and platform interface.</p><p>Camera frames and face landmarks stay in your browser. Face tracking positions effects; it does not identify you or infer personality. Identity labels and confidence-like visuals are fictional. The demo portrait is AI-generated.</p><p>No effects or meme audio are active. The face tracker only displays a position guide; it does not identify you or infer personality.</p><label>Share the artwork<input readOnly value={new URL(base,window.location.origin).href} onFocus={e=>e.target.select()}/></label><span className="mono">ARTWORK / NOT A CLAIM ABOUT TIKTOK’S FACE ANALYSIS</span></>}
 {modal==='profile'&&<><span className="mono">YOUR ASSIGNED PROFILE</span><h2>{identity?.name||'Not yet defined.'}</h2><p>{identity?'You did not choose this identity. The system did.':'Enter the artwork to receive a fictional identity.'}</p><div className="profile-tags">{identity?.tags.map(t=><span key={t}>{t}</span>)}</div><p>Objections received: {state.denials}</p>{scanned&&<button className="primary" onClick={()=>{setModal(null);dispatch({type:'reset'});}}>Reset my profile <ArrowCounterClockwise/></button>}</>}
 {modal==='comments'&&<><span className="mono">SIMULATED COMMUNITY</span><h2>Comments</h2>{['That is not who I am.','The system seems very sure.','What happens if I disagree?'].map((c,i)=><div className="comment" key={c}><User size={22}/><div><span>@subject_{String(i+1).padStart(2,'0')}</span><p>{c}</p></div><Heart size={15}/></div>)}<p className="quiet">Fictional comments and engagement counts, part of the artwork.</p></>}
 {modal==='explore'&&<><span className="mono">EFFECT COLLECTION</span><h2>No effects available.</h2><p>All previous effects have been removed.</p></>}
 {modal==='inbox'&&<><span className="mono">SYSTEM MESSAGES</span><h2>We heard you.</h2><div className="comment"><ChatCircle size={23}/><p>{state.denials?'Your objection has been received. No profile changes are required.':'Your personalized world is ready. Your consent to a category was not required.'}</p></div><p className="quiet">A fictional message from a fictional platform.</p></>}
 </dialog>}
 </div>;
}
