import {useCallback,useEffect,useReducer,useRef,useState,type CSSProperties} from 'react';
import {House,Compass,Plus,ChatCircle,User,Heart,ShareNetwork,ArrowUp,ArrowDown,Camera,CameraSlash,X,ArrowCounterClockwise,Info,Check,SpeakerHigh,SpeakerSlash,Play,Pause} from '@phosphor-icons/react';
import {demoPortrait} from './content';
import {INTRO_DURATION_MS,initialExperience,reducer,stopStream} from './experience';
import FaceTracking from './FaceTracking';
const base=import.meta.env.BASE_URL;
export default function App(){
 const [state,dispatch]=useReducer(reducer,initialExperience);const [stream,setStream]=useState<MediaStream|null>(null);const streamRef=useRef<MediaStream|null>(null);const video=useRef<HTMLVideoElement>(null);const clip=useRef<HTMLVideoElement>(null);const requestId=useRef(0);const mounted=useRef(true);
 const [busy,setBusy]=useState(false),[cameraError,setCameraError]=useState(''),[tracking,setTracking]=useState('Camera off'),[toast,setToast]=useState(''),[modal,setModal]=useState<'about'|'profile'|'comments'|'explore'|'inbox'|null>(null),[tab,setTab]=useState<'for-you'|'following'>('for-you');
 const [sound,setSound]=useState(false),[paused,setPaused]=useState(false),[clipError,setClipError]=useState('');
 const [introReady,setIntroReady]=useState(false);const phase=state.phase;const notify=useCallback((message:string)=>setToast(message),[]);const onTracking=useCallback((s:string)=>setTracking(s),[]);
 useEffect(()=>{if(phase!=='intro'||!introReady)return;const timer=setTimeout(()=>dispatch({type:'entered'}),INTRO_DURATION_MS);return()=>clearTimeout(timer);},[phase,introReady]);
 const closeCamera=useCallback(()=>{requestId.current++;stopStream(streamRef.current);streamRef.current=null;setStream(null);setBusy(false);setTracking('Camera off');},[]);
 useEffect(()=>{mounted.current=true;const release=()=>{requestId.current++;stopStream(streamRef.current);streamRef.current=null;setStream(null);};window.addEventListener('pagehide',release);return()=>{mounted.current=false;requestId.current++;stopStream(streamRef.current);window.removeEventListener('pagehide',release);};},[]);
 useEffect(()=>{const v=video.current;if(v&&stream){v.srcObject=stream;v.play().catch(()=>notify('Tap the camera preview to resume playback.'));}return()=>{if(v)v.srcObject=null;};},[stream,phase,notify]);
 useEffect(()=>{const v=clip.current;if(v&&phase==='feed'){v.currentTime=0;setPaused(false);void v.play().catch(()=>setPaused(true));}},[state.index,phase]);
 const replay=()=>{dispatch({type:'reset'});const v=clip.current;if(v){v.currentTime=0;void v.play().then(()=>setPaused(false)).catch(()=>setPaused(true));}};
 const togglePlayback=()=>{const v=clip.current;if(!v)return;if(v.paused)void v.play().then(()=>setPaused(false)).catch(()=>notify('Tap again to play.'));else{v.pause();setPaused(true);}};
 const toggleSound=()=>{const v=clip.current;if(!v)return;v.muted=!v.muted;setSound(!v.muted);void v.play().then(()=>setPaused(false)).catch(()=>setPaused(true));};
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),3200);return()=>clearTimeout(t);},[toast]);
 const enableCamera=async()=>{if(phase!=='feed'||busy)return;const token=++requestId.current;setBusy(true);setCameraError('');try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('unavailable');const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:720},height:{ideal:1280}},audio:false});if(token!==requestId.current||!mounted.current){stopStream(s);return;}stopStream(streamRef.current);streamRef.current=s;setStream(s);setBusy(false);}catch(e){if(token!==requestId.current||!mounted.current)return;setBusy(false);const name=e instanceof DOMException?e.name:'';setCameraError(name==='NotAllowedError'?'Camera permission was declined. You can still explore the artwork in demo mode.':'No camera is available. Try again or continue with the sample head.');}};
 const gestureLock=useRef(0),touchStart=useRef<number|null>(null);const step=useCallback((delta:number)=>{if(phase!=='feed'||modal)return;const now=performance.now();if(now-gestureLock.current<450)return;gestureLock.current=now;dispatch({type:'step',delta});},[phase,modal]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement).matches('input,textarea,select')||modal)return;if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();step(e.key==='ArrowDown'?1:-1);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[step,modal]);
 useEffect(()=>{if(!modal)return;const previous=document.activeElement as HTMLElement;const dialog=document.querySelector<HTMLDialogElement>('dialog');dialog?.showModal();const escape=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();setModal(null);}};window.addEventListener('keydown',escape);return()=>{dialog?.close();previous?.focus();window.removeEventListener('keydown',escape);};},[modal]);
 const share=async()=>{try{await navigator.clipboard.writeText(new URL(base,window.location.origin).href);notify('Artwork link copied.');}catch{setModal('about');notify('Copy the artwork link from About.');}};
 const nav=(value:'home'|'explore'|'create'|'inbox'|'profile')=>{if(value==='home'){setTab('for-you');setModal(null);}if(value==='explore')setModal('explore');if(value==='create'){if(stream)notify('Your camera is already on.');else void enableCamera();}if(value==='inbox')setModal('inbox');if(value==='profile')setModal('profile');};
 if(phase==='intro')return <div className="app"><main className="stage-wrap"><section className="stage intro" aria-label="Opening transition" style={{'--intro-duration':`${INTRO_DURATION_MS}ms`} as CSSProperties}><img className={`intro-art ${introReady?'ready':''}`} src={base+'media/splash-douwai.webp'} alt="抖歪" fetchPriority="high" onLoad={()=>setIntroReady(true)} onError={()=>setIntroReady(true)}/></section></main></div>;
 return <div className="app">
 <main className="stage-wrap"><section className={`stage ${phase} skin-pirate`} aria-label="Interactive artwork" onWheel={e=>{if(Math.abs(e.deltaY)>20)step(e.deltaY>0?1:-1);}} onTouchStart={e=>{touchStart.current=e.touches[0].clientY;}} onTouchEnd={e=>{if(touchStart.current===null)return;const d=touchStart.current-e.changedTouches[0].clientY;if(Math.abs(d)>50)step(d>0?1:-1);touchStart.current=null;}}>
 <div className="portrait-backdrop"><video ref={clip} className="meme-video" src={base+'media/qinghai-original.mp4'} autoPlay loop muted={!sound} playsInline preload="auto" aria-label="Qinghai dance source video" onError={()=>setClipError('Video unavailable · reload to retry')}/></div>
 <video ref={video} className="camera-source" autoPlay muted playsInline aria-label="Local camera input"/>
 <FaceTracking video={video} clip={clip} active={!!stream} onStatus={onTracking}/>
 <div className="portrait-shade"/>
 <div className="bootleg-brand"><strong>DOU.Y1N</strong><span>BOOTLEG VERSION</span></div><header className="stage-header"><div className="feed-tabs"><button className={tab==='following'?'active':''} onClick={()=>{setTab('following');notify('No creators followed. The platform chooses your feed.');}}>Following</button><button className={tab==='for-you'?'active':''} onClick={()=>setTab('for-you')}>For You</button></div><button className="camera-toggle" aria-label={stream?'Turn camera off':'Turn camera on'} onClick={()=>stream?closeCamera():void enableCamera()} disabled={busy}>{stream?<Camera size={18}/>:<CameraSlash size={18}/>}<span>{stream?'LIVE':'DEMO'}</span></button><button className="about-toggle" aria-label="About the artwork" onClick={()=>setModal('about')}><Info size={20}/></button></header>

 <div className="scan-meta"><span>{stream?tracking:'DEMO / SAMPLE FACE'}</span><span>BIG HEAD / LOCAL ONLY</span></div>
 {clipError&&<div className="feed-empty" role="alert">{clipError}</div>}
 <div className="post-caption"><span className="mono">青海摇 · 大头版 · #{String(state.index+1).padStart(3,'0')}</span><p>{stream?'你的脸，平台的动作。':'点右上角摄像头，换成你的脸。'}</p><div className="clip-controls"><button aria-label={paused?'Play video':'Pause video'} onClick={togglePlayback}>{paused?<Play size={16}/>:<Pause size={16}/>}</button><button aria-label={sound?'Mute video':'Unmute video'} onClick={toggleSound}>{sound?<SpeakerHigh size={16}/>:<SpeakerSlash size={16}/>}</button><button className="reset-button" onClick={replay}><ArrowCounterClockwise size={14}/> Reset my feed</button></div></div>
 <div className="action-rail"><button className="avatar" onClick={()=>setModal('profile')} aria-label="View profile"><img src={demoPortrait} alt=""/><span><Plus size={12} weight="bold"/></span></button><button disabled aria-label="Like post"><Heart size={29} weight="fill"/><span>—</span></button><button onClick={()=>setModal('comments')} aria-label="Open comments"><ChatCircle size={29} weight="fill"/><span>4.2K</span></button><button onClick={()=>void share()} aria-label="Share artwork"><ShareNetwork size={28} weight="fill"/><span>9.1K</span></button></div>
 <nav className="bottom-nav" aria-label="Mobile navigation"><button onClick={()=>nav('home')}><House size={23} weight="fill"/><span>Home</span></button><button onClick={()=>nav('explore')}><Compass size={23}/><span>Explore</span></button><button className="create-button" onClick={()=>nav('create')} aria-label="Open camera"><Plus size={26} weight="bold"/></button><button onClick={()=>nav('inbox')}><ChatCircle size={23}/><span>Inbox</span></button><button onClick={()=>nav('profile')}><User size={23}/><span>Profile</span></button></nav>
 {toast&&<div className="toast" role="status"><Check size={15}/>{toast}</div>}
 {phase==='feed'&&<div className="scroll-controls"><button aria-label="Previous post" disabled={state.index===0} onClick={()=>step(-1)}><ArrowUp/></button><button aria-label="Next post" onClick={()=>step(1)}><ArrowDown/></button></div>}</section></main>
 {cameraError&&<div className="camera-error" role="alert"><CameraSlash size={20}/><p>{cameraError}</p><button onClick={()=>{setCameraError('');}}>Continue in demo</button><button aria-label="Dismiss camera notice" onClick={()=>setCameraError('')}><X/></button></div>}
 {modal&&<dialog className="dialog" onCancel={()=>setModal(null)} onClick={e=>{if(e.target===e.currentTarget)setModal(null);}}><button className="dialog-close" onClick={()=>setModal(null)} aria-label="Close dialog"><X size={23}/></button>
 {modal==='about'&&<><span className="mono">BEHIND THE EXPERIMENT</span><h2>For you.<br/>According to whom?</h2><p>FOR YOU is a fictional platform and interactive artwork inspired by TikTok / Douyin. This trial uses the supplied Qinghai dance video and an exaggerated head overlay. There is currently one clip; scrolling replays it, rather than pretending it is a new video.</p><p>Camera frames and face landmarks stay in your browser. Face tracking positions effects; it does not identify you or infer personality. No identity is assigned or inferred. The demo portrait is AI-generated.</p><p>The original video supplies the body, movement and sound. Camera frames are cropped and composited locally; they are never uploaded. Camera use is optional. Demo mode uses a fictional AI-generated male head. This is a playful 2D collage, not a seamless neural face swap.</p><label>Share the artwork<input readOnly value={new URL(base,window.location.origin).href} onFocus={e=>e.target.select()}/></label><span className="mono">ARTWORK / NOT A CLAIM ABOUT TIKTOK’S FACE ANALYSIS</span></>}
 {modal==='profile'&&<><span className="mono">PROFILE</span><h2>Guest</h2><p>No account or assigned identity. Camera frames stay on your device.</p><p>Camera: {stream?'on':'off'}</p></>}
 {modal==='comments'&&<><span className="mono">SIMULATED COMMUNITY</span><h2>Comments</h2>{['That is not who I am.','The system seems very sure.','What happens if I disagree?'].map((c,i)=><div className="comment" key={c}><User size={22}/><div><span>@subject_{String(i+1).padStart(2,'0')}</span><p>{c}</p></div><Heart size={15}/></div>)}<p className="quiet">Fictional comments and engagement counts, part of the artwork.</p></>}
 {modal==='explore'&&<><span className="mono">EFFECT COLLECTION</span><h2>青海摇 · 大头版</h2><p>1 clip · Your face, somebody else’s moves.</p><button className="primary" onClick={()=>{setModal(null);replay();}}>Play</button></>}
 {modal==='inbox'&&<><span className="mono">SYSTEM MESSAGES</span><h2>No messages.</h2><p>Camera is optional. No sign-in is required.</p></>}
 </dialog>}
 </div>;
}
