import {useEffect,useRef,useState} from 'react';
import {UserPlus,Users,MagnifyingGlass,List,Plus,CaretRight,CaretDown,VideoCamera,ShoppingCart,Clock,Wallet,SquaresFour,Lock,Stack,Play,PushPin,X,Check,Heart,Star,Image,ArrowLeft} from '@phosphor-icons/react';
import {formatCount} from './formatCount';
import type {FeedClip} from './clips';
import './profile.css';
const base=import.meta.env.BASE_URL;
const avatars=['cat','panda','sunset'];
const tabs=['作品','日常','推荐','收藏','喜欢'] as const;
type Tab=typeof tabs[number];
type Props={visible:boolean;clips:readonly FeedClip[];liked:Record<string,boolean>;saved:Record<string,boolean>;watched:readonly string[];onSelect:(index:number)=>void};
export default function Profile({visible,clips,liked,saved,watched,onSelect}:Props){
 const [name,setName]=useState('抖歪放映员'),[bio,setBio]=useState('今日份快乐，正在放映。\n名场面收藏家，快乐不打烊。\n刷到喜欢的，就多看一遍。'),[avatar,setAvatar]=useState('cat');
 const [tab,setTab]=useState<Tab>('作品'),[search,setSearch]=useState(false),[query,setQuery]=useState(''),[panel,setPanel]=useState(''),[daily,setDaily]=useState<string|null>(null);
 const [draftName,setDraftName]=useState(name),[draftBio,setDraftBio]=useState(bio),[draftAvatar,setDraftAvatar]=useState(avatar);
 const dialog=useRef<HTMLDivElement>(null),close=useRef<HTMLButtonElement>(null);
 useEffect(()=>{if(!visible){setPanel('');setDaily(null);return;}const escape=(e:KeyboardEvent)=>{if(e.key==='Escape'){setPanel('');setDaily(null);setSearch(false);}};window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape);},[visible]);
 useEffect(()=>{if(!panel&&!daily)return;const previous=document.activeElement as HTMLElement;close.current?.focus();const trap=(e:KeyboardEvent)=>{if(e.key!=='Tab')return;const items=[...dialog.current?.querySelectorAll<HTMLElement>('button,input,textarea')??[]].filter(x=>!x.hasAttribute('disabled'));if(!items.length)return;const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}};window.addEventListener('keydown',trap);return()=>{window.removeEventListener('keydown',trap);previous?.focus();};},[panel,daily]);
 const edit=()=>{setDraftName(name);setDraftBio(bio);setDraftAvatar(avatar);setPanel('编辑主页');};
 const filtered=clips.map((clip,index)=>({clip,index})).filter(({clip})=>(tab!=='收藏'||saved[clip.id])&&(tab!=='喜欢'||liked[clip.id])&&clip.title.toLowerCase().includes(query.trim().toLowerCase()));
 if(!visible)return null;
 const utilities=[{label:'主播中心',Icon:VideoCamera},{label:'我的订单',Icon:ShoppingCart},{label:'观看历史',Icon:Clock},{label:'我的钱包',Icon:Wallet},{label:'全部功能',Icon:SquaresFour}];
 const descriptions:Record<string,string>={'添加好友':'这里是虚构好友演示。去「消息」看看奶龙、牢大和篮球粉丝们的聊天吧。','新访客':'今天有 3 位演示访客来过：奶龙放映室、篮球放映员、快乐收集站。','主播中心':'还没有开播记录。这里展示主播中心的页面入口。','我的订单':'暂无订单。演示页面不提供购物服务。','观看历史':watched.length?'本次观看过的片段，点击就能再次播放。':'还没有观看记录。去首页看看吧。','我的钱包':'暂无账单。演示页面不支持充值、提现或付款。','全部功能':'收藏喜欢的片段，编辑演示资料，或从作品网格选择视频。','私密作品':'暂无私密作品。这里没有上传或保存私人视频。','合集管理':`当前合集共 ${clips.length} 条视频，均来自本分区。`,'放映计划':'今日计划：把快乐看完，把喜欢留下。','主页菜单':'抖歪 · 课程演示\n资料和互动仅保留在本次页面中。这里没有真实账号，刷新后恢复演示资料。','互关':'12 位演示好友：快乐收集站、奶龙放映室、篮球放映员等。','关注':'48 位演示关注，等着一起看名场面。','粉丝':'128 位演示粉丝，快乐正在集合。','获赞':'1.6 万次演示获赞。感谢每一份快乐。'};
 return <section className="profile-page" aria-label="个人主页">
 <div className="profile-scroll" inert={!!panel||!!daily}>
 <header className="profile-cover">
 <img className="profile-cover-image" src={base+'media/avatar-sunset.webp'} alt="夕阳山峦封面"/>
 <div className="profile-toolbar"><button onClick={()=>setPanel('添加好友')}><UserPlus size={18}/><span>添加好友</span></button><div><button onClick={()=>setPanel('新访客')} aria-label="新访客"><Users size={19}/><span>新访客 3</span></button><button aria-label="搜索主页作品" onClick={()=>{setSearch(v=>!v);setQuery('');}}><MagnifyingGlass size={22}/></button><button aria-label="主页菜单" onClick={()=>setPanel('主页菜单')}><List size={23}/></button></div></div>
 <div className="profile-identity"><button className="profile-avatar" aria-label="更换演示头像" onClick={edit}><img src={base+`media/avatar-${avatar}.webp`} alt="演示动物或风景头像"/><span><Plus size={20} weight="bold"/></span></button><div><h1>{name}</h1><p>抖歪号：douwai_demo</p><button className="profile-badge" onClick={()=>setPanel('主页菜单')}>快乐放映中 <CaretRight size={14}/></button></div></div>
 </header>
 <div className="profile-body">
 <div className="profile-stats">{[['1.6万','获赞'],['12','互关'],['48','关注'],['128','粉丝']].map(([value,label])=><button key={label} onClick={()=>setPanel(label)}><strong>{value}</strong><span>{label}</span></button>)}<button className="profile-edit" onClick={edit}>编辑主页</button></div>
 <p className="profile-bio">{bio}</p><div className="profile-tags"><span>快乐星球</span><button onClick={edit}><Plus size={13}/> 名场面收藏家</button><small>虚构资料</small></div>
 <div className="profile-utilities">{utilities.map(({label,Icon})=><button key={label} onClick={()=>setPanel(label)}><Icon size={25} weight="regular"/><span>{label}</span></button>)}</div>
 <div className="profile-tabs" role="tablist" aria-label="主页内容">{tabs.map(label=><button key={label} role="tab" id={'profile-tab-'+label} aria-selected={tab===label} aria-controls="profile-content" className={tab===label?'active':''} onClick={()=>{setTab(label);setQuery('');}}>{label}{label==='作品'&&<CaretDown size={11} weight="fill"/>}</button>)}</div>
 {search&&<label className="profile-search"><MagnifyingGlass size={18}/><input autoFocus placeholder="搜索当前分区作品" aria-label="搜索当前分区作品" value={query} onChange={e=>setQuery(e.target.value)}/><button aria-label="关闭搜索" onClick={()=>{setSearch(false);setQuery('');}}><X size={18}/></button></label>}
 <div id="profile-content" role="tabpanel" aria-labelledby={'profile-tab-'+tab}>
 {tab==='作品'&&<div className="profile-management"><button onClick={()=>setPanel('私密作品')}><Lock size={16}/>私密作品 <span>0</span><CaretRight size={12}/></button><button onClick={()=>setPanel('合集管理')}><Stack size={17}/>合集管理</button><button onClick={()=>setPanel('放映计划')}><VideoCamera size={17}/>放映计划</button></div>}
 {tab==='日常'?<div className="profile-grid">{avatars.map((item,i)=><button className="profile-tile" key={item} onClick={()=>setDaily(item)} aria-label={'查看日常 '+['快乐小猫','熊猫营业中','落日放映'][i]}><img src={base+`media/avatar-${item}.webp`} alt={['快乐小猫','熊猫营业中','落日放映'][i]}/><span className="profile-tile-top">日常</span><span className="profile-tile-bottom"><Image size={14}/> {['快乐小猫','熊猫营业中','落日放映'][i]}</span></button>)}</div>:filtered.length?<div className="profile-grid">{filtered.map(({clip,index},i)=><button className="profile-tile" key={clip.id} onClick={()=>onSelect(index)} aria-label={'播放 '+clip.title}><img loading={i<3?'eager':'lazy'} src={base+(clip.track?'media/avatar-sunset.webp':`media/posters/${clip.id}.webp`)} alt={clip.track?'受保护视频的风景封面':clip.title}/>{tab==='作品'&&i<2&&<span className="profile-tile-top pinned"><PushPin size={10} weight="fill"/>置顶</span>}<span className="profile-tile-bottom"><Play size={14}/>{formatCount((index+1)*7319+1200)}</span></button>)}</div>:<div className="profile-empty">{tab==='喜欢'?<Heart size={33}/>:<Star size={33}/>}<p>{query?'没有找到相关作品':tab==='喜欢'?'还没有喜欢的作品':'还没有收藏的作品'}</p><span>{query?'试试当前分区的视频名称':'在首页点亮图标，就会出现在这里'}</span><button onClick={()=>{setQuery('');setTab('作品');}}>看看作品</button></div>}
 <p className="profile-footnote">{tab==='日常'?'演示日常 · 公共动物与风景素材':`${clips.length} 条本分区原视频 · 演示作品`}</p>
 </div></div></div>
 {(panel||daily)&&<div className="profile-overlay" onClick={e=>{if(e.target===e.currentTarget){setPanel('');setDaily(null);}}}><div ref={dialog} className="profile-sheet" role="dialog" aria-modal="true" aria-label={panel||'日常预览'}><header><button ref={close} aria-label="关闭主页面板" onClick={()=>{setPanel('');setDaily(null);}}><ArrowLeft size={22}/></button><h2>{panel||'日常'}</h2><span/></header>
 {panel==='编辑主页'?<form onSubmit={e=>{e.preventDefault();setName(draftName.trim());setBio(draftBio.trim());setAvatar(draftAvatar);setPanel('');}}><div className="profile-avatar-picker">{avatars.map(item=><button type="button" key={item} aria-label={'选择'+item+'头像'} aria-pressed={draftAvatar===item} onClick={()=>setDraftAvatar(item)}><img src={base+`media/avatar-${item}.webp`} alt=""/>{draftAvatar===item&&<Check size={16}/>}</button>)}</div><label>昵称<input required maxLength={20} value={draftName} onChange={e=>setDraftName(e.target.value)}/></label><label>简介<textarea maxLength={100} rows={4} value={draftBio} onChange={e=>setDraftBio(e.target.value)}/></label><p className="profile-note">仅修改本次页面的演示资料，刷新后恢复。</p><button className="profile-save" disabled={!draftName.trim()} type="submit">保存</button></form>:daily?<><img className="profile-daily-preview" src={base+`media/avatar-${daily}.webp`} alt="公共动物或风景日常"/><p className="profile-note">日常演示 · 公共素材</p></>:<><p className="profile-panel-copy">{descriptions[panel]}</p>{(panel==='合集管理'||panel==='观看历史')&&<div className="profile-collection">{clips.map((item,i)=>({item,i})).filter(({item})=>panel!=='观看历史'||watched.includes(item.id)).map(({item,i})=><button key={item.id} onClick={()=>{setPanel('');onSelect(i);}}><Play size={16}/>{item.title}<CaretRight size={16}/></button>)}</div>}<p className="profile-note">本地演示 · 非真实账号</p></>}
 </div></div>}
 </section>;
}
